In [7]:

import pandas as pd
# code that had be used for extracting the data

# Corona
# print("Corona Düsseldorf")
#df = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS/VSCode/techLabs/Datasets/Raw/Corona/duesseldorf_corona.csv")

#display(df)
#print(df)

# Airquality Particulate Matter

print("Airquality Particulate Matter - 2020 - 2022")
df = pd.read_csv("/Users/selinaycengiz/Documents/TechLabs Group 2/TechsLabTeam2/Test/2010-2019_Ozon_NRW_Stundenmittelwert.csv", encoding="ISO-8859-1", sep=";", header=None)

#print(df.dtypes)

display(df)

# delete the first 2 lines
df = df.drop([0, 1]).reset_index(drop=True)

display(df)
#print(df)

Airquality Particulate Matter - 2020 - 2022

/var/folders/7v/_l30msh559v3md8xfz89t3q80000gn/T/ipykernel_1459/2718187643.py:14: DtypeWarning: Columns (8,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/selinaycengiz/Documents/TechLabs Group 2/TechsLabTeam2/Test/2010-2019_Ozon_NRW_Stundenmittelwert.csv", encoding="ISO-8859-1", sep=";", header=None)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,"# ""Tabelle für Zeitbereich: 01.01.2010 00:00 b...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"# ""Quelle""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Datum,Zeit,AABU O3 1H Mittelwert [µg/m³],BIEL O3 1H Mittelwert [µg/m³],BORG O3 1H Mittelwert [µg/m³],BOTT O3 1H Mittelwert [µg/m³],CHOR O3 1H Mittelwert [µg/m³],DMD2 O3 1H Mittelwert [µg/m³],DWER O3 1H Mittelwert [µg/m³],EIFE O3 1H Mittelwert [µg/m³],...,ROTH O3 1H Mittelwert [µg/m³],SHW2 O3 1H Mittelwert [µg/m³],SICK O3 1H Mittelwert [µg/m³],SOES O3 1H Mittelwert [µg/m³],SOLI O3 1H Mittelwert [µg/m³],STYR O3 1H Mittelwert [µg/m³],VESN O3 1H Mittelwert [µg/m³],WALS O3 1H Mittelwert [µg/m³],WESE O3 1H Mittelwert [µg/m³],WULA O3 1H Mittelwert [µg/m³]
3,01.01.2010,01:00,13,NaN,54,24,NaN,20,NaN,18,...,<4,44,41,45,20,NaN,NaN,31,52,NaN
4,01.01.2010,02:00,20,43,56,38,19,34,NaN,19,...,6,42,NaN,47,30,33,NaN,44,53,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87646,31.12.2019,20:00,5,20,33,37,5,53,6,18,...,42,48,<4,49,32,30,NaN,<4,6,37
87647,31.12.2019,21:00,<4,19,21,39,4,50,<4,31,...,51,35,<4,47,30,19,NaN,<4,<4,13
87648,31.12.2019,22:00,8,18,33,27,4,39,<4,35,...,58,25,<4,41,35,20,NaN,<4,<4,<4
87649,31.12.2019,23:00,9,26,27,13,<4,36,NaN,NaN,...,61,NaN,5,39,28,NaN,NaN,<4,<4,<4
87650,31.12.2019,24:00:00,8,27,NaN,8,<4,19,<4,48,...,59,7,<4,43,24,16,NaN,<4,7,9

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Datum,Zeit,AABU O3 1H Mittelwert [µg/m³],BIEL O3 1H Mittelwert [µg/m³],BORG O3 1H Mittelwert [µg/m³],BOTT O3 1H Mittelwert [µg/m³],CHOR O3 1H Mittelwert [µg/m³],DMD2 O3 1H Mittelwert [µg/m³],DWER O3 1H Mittelwert [µg/m³],EIFE O3 1H Mittelwert [µg/m³],...,ROTH O3 1H Mittelwert [µg/m³],SHW2 O3 1H Mittelwert [µg/m³],SICK O3 1H Mittelwert [µg/m³],SOES O3 1H Mittelwert [µg/m³],SOLI O3 1H Mittelwert [µg/m³],STYR O3 1H Mittelwert [µg/m³],VESN O3 1H Mittelwert [µg/m³],WALS O3 1H Mittelwert [µg/m³],WESE O3 1H Mittelwert [µg/m³],WULA O3 1H Mittelwert [µg/m³]
1,01.01.2010,01:00,13,NaN,54,24,NaN,20,NaN,18,...,<4,44,41,45,20,NaN,NaN,31,52,NaN
2,01.01.2010,02:00,20,43,56,38,19,34,NaN,19,...,6,42,NaN,47,30,33,NaN,44,53,33
3,01.01.2010,03:00,28,44,59,43,22,38,NaN,25,...,11,41,54,48,28,43,NaN,46,57,34
4,01.01.2010,04:00,31,47,62,44,20,35,NaN,NaN,...,18,43,54,NaN,36,42,NaN,48,58,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87644,31.12.2019,20:00,5,20,33,37,5,53,6,18,...,42,48,<4,49,32,30,NaN,<4,6,37
87645,31.12.2019,21:00,<4,19,21,39,4,50,<4,31,...,51,35,<4,47,30,19,NaN,<4,<4,13
87646,31.12.2019,22:00,8,18,33,27,4,39,<4,35,...,58,25,<4,41,35,20,NaN,<4,<4,<4
87647,31.12.2019,23:00,9,26,27,13,<4,36,NaN,NaN,...,61,NaN,5,39,28,NaN,NaN,<4,<4,<4
87648,31.12.2019,24:00:00,8,27,NaN,8,<4,19,<4,48,...,59,7,<4,43,24,16,NaN,<4,7,9