In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
# Hotel inkl. Country Codes (hotel shape war: 119390 rows × 32 columns, jetzt plus 5 Spalten für Country Codes Merge)
df_hotel = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS_2/TechsLabTeam2/Data/Edited/Hotel_CountryCodes.csv", encoding="ISO-8859-1")


#Spaltennamen umändern, damit sie zu Happiness passen
df_hotel.rename(columns={'arrival_date_year': 'Year', "country_common" : "Country"}, inplace=True)

display(df_hotel)

,iso2,iso3,iso_num,country_x,Country,hotel,is_canceled,lead_time,Year,arrival_date_month,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,PT,PRT,620.0,Portugal,Portugal,Resort Hotel,0,342,2015,July,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,PT,PRT,620.0,Portugal,Portugal,Resort Hotel,0,737,2015,July,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,Resort Hotel,0,7,2015,July,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,Resort Hotel,0,13,2015,July,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,Resort Hotel,0,14,2015,July,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,BE,BEL,56.0,Belgium,Belgium,City Hotel,0,23,2017,August,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,FR,FRA,250.0,France,France,City Hotel,0,102,2017,August,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,DE,DEU,276.0,Germany,Germany,City Hotel,0,34,2017,August,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,City Hotel,0,109,2017,August,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,DE,DEU,276.0,Germany,Germany,City Hotel,0,205,2017,August,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [5]:
df_2015 = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS_2/TechsLabTeam2/Data/Raw/Happiness/World Happiness/2015.csv")
df_2015['Year'] = 2015  # Hinzufügen einer Spalte mit dem Jahr 2015
df_2016 = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS_2/TechsLabTeam2/Data/Raw/Happiness/World Happiness/2016.csv")
df_2016['Year'] = 2016  # Hinzufügen einer Spalte mit dem Jahr 2016
df_2017 = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS_2/TechsLabTeam2/Data/Raw/Happiness/World Happiness/2017_2.csv", sep=";" )
df_2017['Year'] = 2017  # Hinzufügen einer Spalte mit dem Jahr 2017

#print(df_2015.head())
#print(df_2016.head())
print(df_2017.head())

       Country  Happiness Rank  Happiness Score  Whisker high  Whisker low  \
0       Norway               1            7.537      7.594445     7.479556
1      Denmark               2            7.522      7.581728     7.462272
2      Iceland               3            7.504      7.622030     7.385970
3  Switzerland               4            7.494      7.561772     7.426227
4      Finland               5            7.469      7.527542     7.410458

   Economy (GDP per Capita)    Family  Health (Life Expectancy)   Freedom  \
0                  1.616463  1.533524                  0.796667  0.635423
1                  1.482383  1.551122                  0.792566  0.626007
2                  1.480633  1.610574                  0.833552  0.627163
3                  1.564980  1.516912                  0.858131  0.620071
4                  1.443572  1.540247                  0.809158  0.617951

   Generosity  Trust (Government Corruption)  Dystopia Residual  Year
0    0.362012                       0.315964           2.277027  2017
1    0.355280                       0.400770           2.313707  2017
2    0.475540                       0.153527           2.322715  2017
3    0.290549                       0.367007           2.276716  2017
4    0.245483                       0.382612           2.430182  2017

In [6]:
# Anzeigen der vorhandenen Spaltennamen in df_2015
print("Spaltennamen in df_2015:", df_2015.columns)

# Anzeigen der vorhandenen Spaltennamen in df_2016
print("Spaltennamen in df_2016:", df_2016.columns)

# Anzeigen der vorhandenen Spaltennamen in df_2017
print("Spaltennamen in df_2017:", df_2017.columns)

Spaltennamen in df_2015: Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year'],
      dtype='object')
Spaltennamen in df_2016: Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual', 'Year'],
      dtype='object')
Spaltennamen in df_2017: Index(['Country', 'Happiness Rank', 'Happiness Score', 'Whisker high',
       'Whisker low', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Generosity',
       'Trust (Government Corruption)', 'Dystopia Residual', 'Year'],
      dtype='object')

In [7]:
# Bereinigen der Spaltennamen von Leerzeichen am Anfang oder Ende
df_2015.columns = df_2015.columns.str.strip()
df_2016.columns = df_2016.columns.str.strip()
df_2017.columns = df_2017.columns.str.strip()

In [9]:
# Entfernen der gewünschten Spalten

# Direktes Löschen der Spalte 
if 'Standard Error' in df_2015.columns:
    del df_2015['Standard Error']

# Anzeigen der DataFrame-Kopfzeilen nach Entfernung der Spalte
print(df_2015.head())


if 'Standard Error' in df_2015.columns:
    del df_2015['Standard Error']

# Anzeigen der DataFrame-Kopfzeilen nach Entfernung der Spalte
print(df_2015.head())


# Überprüfen und Entfernen der gewünschten Spalten in df_2016
columns_to_remove_2016 = ['Lower Confidence Interval', 'Upper Confidence Interval']
for column in columns_to_remove_2016:
    if column in df_2016.columns:
        df_2016 = df_2016.drop([column], axis=1)

# Überprüfen und Entfernen der gewünschten Spalten in df_2017
columns_to_remove_2017 = ['Whisker high', 'Whisker low']
for column in columns_to_remove_2017:
    if column in df_2017.columns:
        df_2017 = df_2017.drop([column], axis=1)

# Zusammenführen der DataFrames
df_happiness = pd.concat([df_2015, df_2016, df_2017], ignore_index=True)

print(df_happiness)

# Speichern als CSV-Datei
#df_happiness.to_csv('/Users/carareusch/Desktop/TechsLabTeam2/TechsLabTeam2-3/Data/Edited/Combined_Happiness.csv', index=False)

       Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587
1      Iceland  Western Europe               2            7.561
2      Denmark  Western Europe               3            7.527
3       Norway  Western Europe               4            7.522
4       Canada   North America               5            7.427

   Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                   1.39651  1.34951                   0.94143  0.66557
1                   1.30232  1.40223                   0.94784  0.62877
2                   1.32548  1.36058                   0.87464  0.64938
3                   1.45900  1.33095                   0.88521  0.66973
4                   1.32629  1.32261                   0.90563  0.63297

   Trust (Government Corruption)  Generosity  Dystopia Residual  Year
0                        0.41978     0.29678            2.51738  2015
1                        0.14145     0.43630            2.70201  2015
2                        0.48357     0.34139            2.49204  2015
3                        0.36503     0.34699            2.46531  2015
4                        0.32957     0.45811            2.45176  2015
       Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587
1      Iceland  Western Europe               2            7.561
2      Denmark  Western Europe               3            7.527
3       Norway  Western Europe               4            7.522
4       Canada   North America               5            7.427

   Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                   1.39651  1.34951                   0.94143  0.66557
1                   1.30232  1.40223                   0.94784  0.62877
2                   1.32548  1.36058                   0.87464  0.64938
3                   1.45900  1.33095                   0.88521  0.66973
4                   1.32629  1.32261                   0.90563  0.63297

   Trust (Government Corruption)  Generosity  Dystopia Residual  Year
0                        0.41978     0.29678            2.51738  2015
1                        0.14145     0.43630            2.70201  2015
2                        0.48357     0.34139            2.49204  2015
3                        0.36503     0.34699            2.46531  2015
4                        0.32957     0.45811            2.45176  2015
                      Country          Region  Happiness Rank  \
0                 Switzerland  Western Europe               1
1                     Iceland  Western Europe               2
2                     Denmark  Western Europe               3
3                      Norway  Western Europe               4
4                      Canada   North America               5
..                        ...             ...             ...
465                    Rwanda             NaN             151
466                     Syria             NaN             152
467                  Tanzania             NaN             153
468                   Burundi             NaN             154
469  Central African Republic             NaN             155

     Happiness Score  Economy (GDP per Capita)    Family  \
0              7.587                  1.396510  1.349510
1              7.561                  1.302320  1.402230
2              7.527                  1.325480  1.360580
3              7.522                  1.459000  1.330950
4              7.427                  1.326290  1.322610
..               ...                       ...       ...
465            3.471                  0.368746  0.945707
466            3.462                  0.777153  0.396103
467            3.349                  0.511136  1.041990
468            2.905                  0.091623  0.629794
469            2.693                  0.000000  0.000000

     Health (Life Expectancy)   Freedom  Trust (Government Corruption)  \
0                    0.941430  0.665570                       0.419780
1                    0.947840  0.628770                       0.141450
2                    0.874640  0.649380                       0.483570
3                    0.885210  0.669730                       0.365030
4                    0.905630  0.632970                       0.329570
..                        ...       ...                            ...
465                  0.326425  0.581844                       0.455220
466                  0.500533  0.081539                       0.151347
467                  0.364509  0.390018                       0.066035
468                  0.151611  0.059901                       0.084148
469                  0.018773  0.270842                       0.056565

     Generosity  Dystopia Residual  Year
0      0.296780           2.517380  2015
1      0.436300           2.702010  2015
2      0.341390           2.492040  2015
3      0.346990           2.465310  2015
4      0.458110           2.451760  2015
..          ...                ...   ...
465    0.252756           0.540061  2017
466    0.493664           1.061574  2017
467    0.354256           0.621130  2017
468    0.204435           1.683024  2017
469    0.280876           2.066005  2017

[470 rows x 12 columns]

In [10]:
df_happiness_and_hotel = pd.merge(df_hotel, df_happiness, on=["Country", "Year"], how="left")

#Data cleaning: Alle Buchungen die gecancelt wurden oder wo keine Gäste gekommen sind streichen.
df_happiness_and_hotel = df_happiness_and_hotel[df_happiness_and_hotel["is_canceled"]==0]
df_happiness_and_hotel["total_guests"]= df_happiness_and_hotel["adults"] + df_happiness_and_hotel["children"] + df_happiness_and_hotel["babies"]
df_happiness_and_hotel = df_happiness_and_hotel[df_happiness_and_hotel["total_guests"]!=0]

#display(df_happiness_and_hotel)

print(len(df_hotel))
print(len(df_happiness_and_hotel))

#df_happiness_and_hotel.to_csv('/Users/carareusch/Desktop/TechsLabTeam2/TechsLabTeam2-3/Data/Edited/Happiness_and_Hotel_Combined.csv', index=False)

119390
75011

In [11]:
#show merged data hotel and happiness

display(df_happiness_and_hotel)

,iso2,iso3,iso_num,country_x,Country,hotel,is_canceled,lead_time,Year,arrival_date_month,...,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,total_guests
0,PT,PRT,620.0,Portugal,Portugal,Resort Hotel,0,342,2015,July,...,88.0,5.102,1.159910,1.139350,0.875190,0.514690,0.010780,0.137190,1.264620,2.0
1,PT,PRT,620.0,Portugal,Portugal,Resort Hotel,0,737,2015,July,...,88.0,5.102,1.159910,1.139350,0.875190,0.514690,0.010780,0.137190,1.264620,2.0
2,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,Resort Hotel,0,7,2015,July,...,21.0,6.867,1.266370,1.285480,0.909430,0.596250,0.320670,0.519120,1.969940,1.0
3,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,Resort Hotel,0,13,2015,July,...,21.0,6.867,1.266370,1.285480,0.909430,0.596250,0.320670,0.519120,1.969940,1.0
4,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,Resort Hotel,0,14,2015,July,...,21.0,6.867,1.266370,1.285480,0.909430,0.596250,0.320670,0.519120,1.969940,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,BE,BEL,56.0,Belgium,Belgium,City Hotel,0,23,2017,August,...,17.0,6.891,1.463781,1.462313,0.818092,0.539771,0.251343,0.231503,2.124210,2.0
119386,FR,FRA,250.0,France,France,City Hotel,0,102,2017,August,...,31.0,6.442,1.430923,1.387777,0.844466,0.470222,0.172502,0.129762,2.005955,3.0
119387,DE,DEU,276.0,Germany,Germany,City Hotel,0,34,2017,August,...,16.0,6.951,1.487923,1.472520,0.798951,0.562511,0.276732,0.336269,2.015770,2.0
119388,GB,GBR,826.0,United Kingdom of Great Britain and Northern I...,United Kingdom,City Hotel,0,109,2017,August,...,19.0,6.714,1.441634,1.496460,0.805336,0.508190,0.265428,0.492774,1.704144,2.0
119389,DE,DEU,276.0,Germany,Germany,City Hotel,0,205,2017,August,...,16.0,6.951,1.487923,1.472520,0.798951,0.562511,0.276732,0.336269,2.015770,2.0